### ISSUE TITLE
Allow sending metadata

### ISSUE THREAD

**Issue by AlexITC** [scalapb/scalapb-grpcweb#14]
Right now, the empty metadata is hardcoded, while it could be useful to support sending custom metadata.

On the scala client you can set up an interceptor which can add the metadata before a request is sent, this approach may be feasible on the scalajs client.

One idea to explore is to send cookies and try to setup envoy so that it transforms the cookies in grpc metadata, the drawback is that all request will include the same metadata, while sometimes it's useful to use different metadata per request.

**Comment by thesamet** [comment]
I have squashed PR #20  and made some additional changes that were committed in 52f7fd4780b42883d6787545c34422f1b61d20e3:

* Code gen and core library moved to com.thesamet.scalapb.grpcweb
* The generated code is inside an object name suffixed by `GrpcWeb`, i.e. `MyServiceGrpcWeb`:
* The methods that take metadata and those that don't are generated inside a single trait. I preferred this over default parameters due to the having a default value for a metadata between two required args (request and responseObserver) is odd.
* the new generator needs to run in addition to the existing generator (not to invoke it) for better modularity. If all generators did that, they couldn't be combined to a single run since they all would generate Scala code for message types.

Please check out the latest snapshot and provide feedback if we can close this issue:

**Comment by AlexITC** [comment]
From my tests, it looks good to me, I have submitted a small PR to update minor details

We'll try integrating this internally on a project and get back to you in the next week.

Thanks!

**Comment by thesamet** [comment]
I believe this can be closed.

**Comment by AlexITC** [comment]
I confirm we have been using this successfully for months now.

Thanks!
